return {
	["환영합니다!"]="Welcome!",
	["왼쪽 <스틱>으로 플레이어를 움직여보세요."]="Use the left <STICK> to move yourself.",
	["흰색 공과 부딪쳐보세요. (%d/%d)"]="Hit the white ball. (%d/%d)",
	["잘했습니다!"]="Good!",
	["<대시>를 사용해 공과 부딪쳐보세요. (%d/%d)"]="Hit the white ball using <DASH>. (%d/%d)",
	["아주 잘했습니다!"]="Very good!",
	["그럼 <타워>를 소환하겠습니다."]="Let me summon <TOWERS>.",
	["왼쪽 하단에 생긴 것은 <아군 타워>입니다."]="On the bottom left, there is a <FRIENDLY TOWER>.",
	["오른쪽 상단에 생긴 것은 <적군 타워>입니다."]="On the upper right, there is an <ENEMY TOWER>.",
	["공으로 <적군 타워>에 데미지를 입히세요. (%d/%d)"]="Attack the <ENEMY TOWER> by hitting the ball. (%d/%d)",
	["대단히 잘했습니다!"]="Excellent!",
	["마지막으로 <적 플레이어>을 소환하겠습니다."]="Let me summon the <ENEMY>.",
	["적의 방해를 피해 <적군 타워>를 파괴하십시오!"]="Destroy the <ENEMY TOWER>!",
	["축하합니다! 실전에서도 건투를 빕니다."]="Congratulations! Touch <BACK> to proceed.",
	["상대방을 찾는 중..."]="Searching opponent...",
	["STR_POINTS_ACQUIRED"]="%d %s acquired!",
	["STR_POINTS_LOST"]="%d %s lost!",
	["STR_POINTS_SINGULAR"]="point",
	["STR_POINTS_PLURAL"]="points",
}