#pragma once

typedef enum _LW_GAME_SCENE {
	LGS_INVALID,
	LGS_BATTLE,
	LGS_FIELD,
	LGS_DIALOG,
	LGS_FONT_TEST,
    LGS_TTL,
	LGS_ADMIN,
	LGS_BATTLE_RESULT,
	LGS_SKIN,
	LGS_PUCK_GAME,
	LGS_PARTICLE_SYSTEM,
	LGS_UI,
	LGS_SPLASH,
    LGS_LEADERBOARD,
    LGS_REMTEX,
} LW_GAME_SCENE;
