#pragma once

typedef enum _LW_UI_ALIGN {
	LTBA_LEFT_TOP, LTBA_CENTER_TOP, LTBA_RIGHT_TOP,
	LTBA_LEFT_CENTER, LTBA_CENTER_CENTER, LTBA_RIGHT_CENTER,
	LTBA_LEFT_BOTTOM, LTBA_CENTER_BOTTOM, LTBA_RIGHT_BOTTOM,
} LW_UI_ALIGN;

