#pragma once
#ifdef __cplusplus
extern "C" {;
#endif
#include "lwvbotype.h"

typedef struct _LWCONTEXT LWCONTEXT;

void render_solid_box_ui_lvt_flip_y_uv(const LWCONTEXT* pLwc,
                                       float x,
                                       float y,
                                       float w,
                                       float h,
                                       GLuint tex_index,
                                       enum _LW_VBO_TYPE lvt,
                                       int flip_y_uv);
void render_solid_box_ui(const LWCONTEXT* pLwc,
                         float x,
                         float y,
                         float w,
                         float h,
                         GLuint tex_index);
void render_solid_box_ui_alpha(const LWCONTEXT* pLwc,
                               float x,
                               float y,
                               float w,
                               float h,
                               GLuint tex_index,
                               float alpha_multiplier);
void render_solid_vb_ui(const LWCONTEXT* pLwc,
                        float x,
                        float y,
                        float w,
                        float h,
                        GLuint tex_index,
                        enum _LW_VBO_TYPE lvt,
                        float alpha_multiplier,
                        float over_r,
                        float over_g,
                        float over_b,
                        float oratio);
void render_solid_vb_ui_alpha(const LWCONTEXT* pLwc,
                              float x,
                              float y,
                              float w,
                              float h,
                              GLuint tex_index,
                              GLuint tex_alpha_index,
                              enum _LW_VBO_TYPE lvt,
                              float alpha_multiplier,
                              float over_r,
                              float over_g,
                              float over_b,
                              float oratio);
void render_solid_vb_ui_flip_y_uv(const LWCONTEXT* pLwc,
                                  float x,
                                  float y,
                                  float w,
                                  float h,
                                  GLuint tex_index,
                                  enum _LW_VBO_TYPE lvt,
                                  float alpha_multiplier,
                                  float over_r,
                                  float over_g,
                                  float over_b,
                                  float oratio,
                                  int flip_y_uv);
void render_solid_vb_ui_flip_y_uv_shader(const LWCONTEXT* pLwc,
                                         float x,
                                         float y,
                                         float w,
                                         float h,
                                         GLuint tex_index,
                                         enum _LW_VBO_TYPE lvt,
                                         float alpha_multiplier,
                                         float over_r,
                                         float over_g,
                                         float over_b,
                                         float oratio,
                                         int flip_y_uv,
                                         int shader_index);
void render_solid_vb_ui_flip_y_uv_shader_rot(const LWCONTEXT* pLwc,
                                             float x,
                                             float y,
                                             float w,
                                             float h,
                                             GLuint tex_index,
                                             enum _LW_VBO_TYPE lvt,
                                             float alpha_multiplier,
                                             float over_r,
                                             float over_g,
                                             float over_b,
                                             float oratio,
                                             int flip_y_uv,
                                             int shader_index,
                                             float rot);
void render_solid_vb_ui_alpha_uv(const LWCONTEXT* pLwc,
                                 float x,
                                 float y,
                                 float w,
                                 float h,
                                 GLuint tex_index,
                                 GLuint tex_alpha_index,
                                 enum _LW_VBO_TYPE lvt,
                                 float alpha_multiplier,
                                 float over_r,
                                 float over_g,
                                 float over_b,
                                 float oratio,
                                 const float* uv_offset,
                                 const float* uv_scale);
void render_solid_vb_ui_alpha_uv_shader_view_proj(const LWCONTEXT* pLwc,
                                                  float x,
                                                  float y,
                                                  float w,
                                                  float h,
                                                  GLuint tex_index,
                                                  GLuint tex_alpha_index,
                                                  enum _LW_VBO_TYPE lvt,
                                                  float alpha_multiplier,
                                                  float over_r,
                                                  float over_g,
                                                  float over_b,
                                                  float oratio,
                                                  const float* uv_offset,
                                                  const float* uv_scale,
                                                  int shader_index,
                                                  const mat4x4 view,
                                                  const mat4x4 proj);
void render_solid_vb_ui_alpha_uv_shader(const LWCONTEXT* pLwc,
                                        float x,
                                        float y,
                                        float w,
                                        float h,
                                        GLuint tex_index,
                                        GLuint tex_alpha_index,
                                        enum _LW_VBO_TYPE lvt,
                                        float alpha_multiplier,
                                        float over_r,
                                        float over_g,
                                        float over_b,
                                        float oratio,
                                        const float* uv_offset,
                                        const float* uv_scale,
                                        int shader_index);
void render_solid_vb_ui_uv_shader_rot(const LWCONTEXT* pLwc,
                                      float x,
                                      float y,
                                      float w,
                                      float h,
                                      GLuint tex_index,
                                      enum _LW_VBO_TYPE lvt,
                                      float alpha_multiplier,
                                      float over_r,
                                      float over_g,
                                      float over_b,
                                      float oratio,
                                      const float* uv_offset,
                                      const float* uv_scale,
                                      int shader_index,
                                      float rot);
void render_solid_vb_ui_uv_shader_rot_view_proj(const LWCONTEXT* pLwc,
                                                float x,
                                                float y,
                                                float w,
                                                float h,
                                                GLuint tex_index,
                                                enum _LW_VBO_TYPE lvt,
                                                float alpha_multiplier,
                                                float over_r,
                                                float over_g,
                                                float over_b,
                                                float oratio,
                                                const float* uv_offset,
                                                const float* uv_scale,
                                                int shader_index,
                                                float rot_z,
                                                const mat4x4 view,
                                                const mat4x4 proj);
void render_solid_vb_uv_shader_rot_view_proj(const LWCONTEXT* pLwc,
                                             float x,
                                             float y,
                                             float z,
                                             float sx,
                                             float sy,
                                             float sz,
                                             GLuint tex_index,
                                             enum _LW_VBO_TYPE lvt,
                                             float alpha_multiplier,
                                             float over_r,
                                             float over_g,
                                             float over_b,
                                             float oratio,
                                             const float* uv_offset,
                                             const float* uv_scale,
                                             int shader_index,
                                             float rot_z,
                                             const mat4x4 view,
                                             const mat4x4 proj);
void render_solid_general(const LWCONTEXT* pLwc,
                          float x,
                          float y,
                          float z,
                          float sx,
                          float sy,
                          float sz,
                          GLuint tex_index,
                          GLuint tex_alpha_index,
                          int lvt,
                          float alpha_multiplier,
                          float over_r,
                          float over_g,
                          float over_b,
                          float oratio,
                          const float* uv_offset,
                          const float* uv_scale,
                          int shader_index,
                          float rot_z,
                          const mat4x4 view,
                          const mat4x4 proj);
void lwc_enable_additive_blending();
void lwc_disable_additive_blending();
void render_solid_general_mvp(const LWCONTEXT* pLwc,
                              GLuint tex_index,
                              GLuint tex_alpha_index,
                              int lvt,
                              float alpha_multiplier,
                              float over_r,
                              float over_g,
                              float over_b,
                              float oratio,
                              const float* uv_offset,
                              const float* uv_scale,
                              int shader_index,
                              const mat4x4 model,
                              const mat4x4 view,
                              const mat4x4 proj);
#ifdef __cplusplus
}
#endif
